<a href="https://colab.research.google.com/github/rohitharya/datavisualizationprac/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NUMPY

In [2]:
import numpy as np

basic numpy array

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a=np.array([1,2,3,4])

In [5]:
b=np.array([5,6,7,8])

In [6]:
a[0]

1

In [7]:
a[:]

array([1, 2, 3, 4])

In [8]:
a[:3]

array([1, 2, 3])

In [9]:
a[:4]

array([1, 2, 3, 4])

In [10]:
a[[0,2,-1]] #multiindexing

array([1, 3, 4])

Array Types

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('int64')

In [14]:
np.array(b,dtype=np.float)

array([5., 6., 7., 8.])

Dimention an shapes

In [15]:
C=np.array([[1,2,3,],[4,5,6]])

In [16]:
C.shape

(2, 3)

In [17]:
C.size #gives number of elements

6

In [18]:
C.ndim

2

In [19]:
d=np.array([
            [1,2,3]
          ,[4,5,6]
          ,[7,8,9]
])

In [20]:
d[0]

array([1, 2, 3])

In [21]:
d[0][0]

1

In [22]:
d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
d[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
d[:2,1:3]

array([[2, 3],
       [5, 6]])

In [26]:
d[1]=np.array([11,12,13])

In [27]:
d

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 7,  8,  9]])

In [28]:
d.sum() #total sum of the element in the array

66

In [29]:
d.mean()

7.333333333333333

In [30]:
d.std()

4.189935029992179

In [31]:
d.var()

17.555555555555557

In [32]:
d.sum(axis=0) #when axis=0 it give the sum of the corresponding column elements

array([19, 22, 25])

In [33]:
d.sum(axis=1) #when axis=1 it gives the sum of the corresponding row elements

array([ 6, 36, 24])

In [36]:
a=np.arange(5)

In [45]:
a

array([30, 31, 32, 33, 34])

In [46]:
a+10

array([40, 41, 42, 43, 44])

In [47]:
a

array([30, 31, 32, 33, 34])

In [48]:
a+=10

In [49]:
a

array([40, 41, 42, 43, 44])

numpy linear algebra

In [50]:
a=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
])

In [51]:
b=np.array([
            [6,5],
            [4,3],
            [2,1]
])

In [53]:
a.dot(b) #gives dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [54]:
a@b #cross product


array([[20, 14],
       [56, 41],
       [92, 68]])

In [55]:
b.T #transpose

array([[6, 4, 2],
       [5, 3, 1]])